### ISSUE TITLE
When a hidden item is discovered, should its description be printed?

### ISSUE THREAD

**Issue by BethMyre** [ewk/adventure#36]

**Comment by mccarrom** [comment]
I've been using the discovery statement instead of the description to tell the user they have discovered something new. Sometimes we explicitly prompt them to look at it, otherwise it's up to them to look at it if they want to. Sometimes the description really needed to elaborate on the name of the item, although every item has a description. For example when you look at the post-it the discovery statement says the password is written on the post-it. When we look at an object with hiddenObjects == true the discovery statement is printed and the discovered attribute of the hiddenObject is set to true. So even if the player misses that the post-it had the password on it from the discovery statement, when the look at the room next they will see "password" listed and be able to look directly at the password. Does that make sense?
